<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\User;
use Illuminate\Auth\Events\Verified;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class VerifyEmailController extends Controller
{
    /**
     * Mark the user addressed by the signed email link as verified.
     *
     * Verification links must also work when opened on another device or in a
     * browser where the member is not signed in yet. The signed URL proves the
     * link was generated by Cerqle, while the email hash binds it to this user.
     */
    public function __invoke(Request $request, string $id, string $hash): RedirectResponse
    {
        $user = User::findOrFail($id);

        abort_unless(
            hash_equals((string) $hash, sha1($user->getEmailForVerification())),
            403,
            'This email verification link is invalid.'
        );

        if (! $user->hasVerifiedEmail() && $user->markEmailAsVerified()) {
            event(new Verified($user));
        }

        if ($request->user()?->is($user)) {
            return redirect()->intended(route('client.dashboard', absolute: false).'?verified=1');
        }

        if ($request->user()) {
            return redirect('/')->with('status', 'Email verified. Sign out of the current account to sign in as '.$user->email.'.');
        }

        return redirect()->route('login')->with('status', 'Email verified successfully. You can now sign in.');
    }
}
